
# main/static.py
from typing import Any, Dict, List


# ============================================================
# Structured SCHEMA metadata (authoritative)
# ============================================================
# Each table: columns (name->type), id_columns, embedding_columns, relations

domain = [ [],
           [ "developers", "projects", "buildings", "units" ],
           [ "employees", "directors_employees", "hos_employee", "teams", "agents_employee" ],
           [ "customers","customerrequesttrackers",  "customers_deals", ],
           [ "deals", "deals_units", "deals_projects", "deals_customers", "deals_directors", "deals_agents", "buildings"  ],
           ["bookings", "paymentlinks", "projects", "buildings", "units", "employees", "agents_employee", "customers", "brokers" ],
           [ "paymentsplits", "payments", "paymentplandetails", "paymentlinks", "onlinepaymenttransactions", "installmentplans", "instalmentadjusted",
              "paymenttermitems", "paymentterms", "projectpaymentplans", "projectpaymentterms" ]]

# ============================================================
# Consolidated domains (6 sub-agents -> 3)
# ============================================================
# Each entry is the deduplicated union of the original per-domain table
# lists above, grouped by real business cohesion rather than by service
# count: property+deals (deals are inventory transactions on the same
# buildings/units/projects), hr+crm (both "who" entities - internal org
# vs external customers), sales+payment (a booking is the transaction that
# triggers its payments - the two were already sharing the "Booking" error
# label before this consolidation, which is a good sign this pairing was
# always the natural one).
domain_property_deals = sorted(set(domain[1]) | set(domain[4]))
domain_people = sorted(set(domain[2]) | set(domain[3]))
domain_sales_payment = sorted(set(domain[5]) | set(domain[6]))

domain.append(domain_property_deals)   # domain[7]
domain.append(domain_people)           # domain[8]
domain.append(domain_sales_payment)    # domain[9]


SCHEMA: Dict[str, Dict[str, Any]] = {
    "developers": {
        "domain": "property",
        "columns": {
            """id int4 NULL,
	"name" text NULL,
	email text NULL,
	operatorname text NULL,
	phone text NULL,
	portalaccesstype text NULL,
	registrationnumber text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_operatorname ev.vector NULL"""
        }
    },

    "projects": {
        "domain": "property",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	shortname text NULL,
	developerid int4 NULL,
	address text NULL,
	"location" text NULL,
	status text NULL,
	accountnumber text NULL,
	bankaddress text NULL,
	bankbranch text NULL,
	bankname text NULL,
	adminfee text NULL,
	corporateaccountname text NULL,
	corporateaccountnumber text NULL,
	corporatebankaddress text NULL,
	corporatebankbranch text NULL,
	corporatebankname text NULL,
	corporateibannumber text NULL,
	escrowaccountname text NULL,
	ibannumber text NULL,
	currency text NULL,
	isavailabiletoportal text NULL,
	latitude text NULL,
	longitude text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_shortname ev.vector NULL,
	embed_location ev.vector NULL,
	embed_bankaddress ev.vector NULL,
	embed_bankbranch ev.vector NULL,
	embed_bankname ev.vector NULL,
	embed_corporateaccountname ev.vector NULL,
	embed_corporatebankaddress ev.vector NULL,
	embed_corporatebankbranch ev.vector NULL,
	embed_corporatebankname ev.vector NULL,
	embed_escrowaccountname ev.vector NULL,
	embed_isavailabiletoportal ev.vector NULL,
	embed_latitude ev.vector NULL,
	embed_longitude ev.vector NULL,
	embed_address ev.vector NULL"""
        },
        
    },

    "buildings": {
        "domain": "property",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	shortname text NULL,
	developerid int4 NULL,
	projectid int4 NULL,
	address text NULL,
	"location" text NULL,
	status text NULL,
	accountnumber text NULL,
	bankaddress text NULL,
	bankbranch text NULL,
	bankname text NULL,
	escrowaccountname text NULL,
	ibannumber text NULL,
	currency text NULL,
	paymenttermid int4 NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_shortname ev.vector NULL,
	embed_location ev.vector NULL,
	embed_bankaddress ev.vector NULL,
	embed_bankbranch ev.vector NULL,
	embed_bankname ev.vector NULL,
	embed_escrowaccountname ev.vector NULL,
	embed_address ev.vector NULL"""
        },

    },

    "units": {
        "domain": "property",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	"number" text NULL,
	buildingid text NULL,
	unitclusterid text NULL,
	availabilitystatus text NULL,
	baths text NULL,
	bedroom text NULL,
	floor text NULL,
	furnished text NULL,
	kitchen text NULL,
	layouthashcode text NULL,
	parking text NULL,
	plotnumber text NULL,
	area text NULL,
	price text NULL,
	pricepersqft text NULL,
	currency text NULL,
	description text NULL,
	"type" text NULL,
	"view" text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_shortname ev.vector NULL,
	embed_availabilitystatus ev.vector NULL,
	embed_bedroom ev.vector NULL,
	embed_furnished ev.vector NULL,
	embed_kitchen ev.vector NULL,
	embed_parking ev.vector NULL,
	embed_description ev.vector NULL,
	embed_type ev.vector NULL,
	embed_view ev.vector NULL"""
        },
        
    },

    "employees": {
        "domain": "organization",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	email text NULL,
	mobile text NULL,
	empcode text NULL,
	nationality text NULL,
	address text NULL,
	"role" text NULL,
	"position" text NULL,
	department text NULL,
	"section" text NULL,
	reportingmanagerid text NULL,
	employmentdate text NULL,
	portalstatus text NULL,
	status text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_nationality ev.vector NULL,
	embed_address ev.vector NULL,
	embed_role ev.vector NULL,
	embed_position ev.vector NULL,
	embed_department ev.vector NULL,
	embed_section ev.vector NULL"""
        },
        
    },
    
    "directors_employees": {
        "domain": "organization",
        "columns": {
            "director_sap": "text",
            "director_id": "int4",
            "director_name": "text",
            "director_email": "text",
            "director_mobile": "text",
            "director_empcode": "text",
            "director_nationality": "text",
            "director_address": "text",
            "director_role": "text",
            "director_position": "text",
            "director_department": "text",
            "director_section": "text",
            "director_reportingmanagerid": "text",
            "director_employmentdate": "text",
            "director_portalstatus": "text",
            "director_status": "text",
            "director_row_txt": "text",
            "director_embedding": "ev.vector",
            "director_embed_name": "ev.vector",
            "director_embed_nationality": "ev.vector",
            "director_embed_address": "ev.vector",
            "director_embed_role": "ev.vector",
            "director_embed_position": "ev.vector",
            "director_embed_department": "ev.vector",
            "director_embed_section": "ev.vector",
            "hos_id": "int4",
            "hos_name": "text",
            "hos_email": "text",
            "hos_mobile": "text",
            "hos_empcode": "text",
            "hos_nationality": "text",
            "hos_address": "text",
            "hos_role": "text",
            "hos_position": "text",
            "hos_department": "text",
            "hos_section": "text",
            "hos_reportingmanagerid": "text",
            "hos_employmentdate": "text",
            "hos_portalstatus": "text",
            "hos_status": "text",
            "hos_row_txt": "text",
            "hos_embedding": "ev.vector",
            "hos_embed_name": "ev.vector",
            "hos_embed_nationality": "ev.vector",
            "hos_embed_address": "ev.vector",
            "hos_embed_role": "ev.vector",
            "hos_embed_position": "ev.vector",
            "hos_embed_department": "ev.vector",
            "hos_embed_section": "ev.vector"
        },

    },

    "hos_employee":  {
        "domain": "organization",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    },

    "brokers": {
        "domain": "brokers-info",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	email text NULL,
	phone text NULL,
	nationality text NULL,
	address text NULL,
	city text NULL,
	country text NULL,
	zipcode text NULL,
	emiratesid text NULL,
	"type" text NULL,
	brokeragecompanyid text NULL,
	website text NULL,
	referred text NULL,
	evrepresentativename text NULL,
	stage text NULL,
	brn text NULL,
	orn text NULL,
	trn text NULL,
	passportexpirydate text NULL,
	passportissueddate text NULL,
	passportnumber text NULL,
	representativeemail text NULL,
	representativemobile text NULL,
	representativename text NULL,
	tradelicensenumber text NULL,
	userssoid text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_nationality ev.vector NULL,
	embed_address ev.vector NULL,
	embed_city ev.vector NULL,
	embed_country ev.vector NULL,
	embed_type ev.vector NULL,
	embed_stage ev.vector NULL"""
        },
        
    },

    "teams": {
        "domain": "organization",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	directorid text NULL,
	sap text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL"""
        },
    },

    "agents_employee": {
            "domain": "organization",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
             "teamid": "text",
            "sap": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    } ,
    
    "customers": {
        "domain": "crm",
        "columns": {"""
	id int4 NULL,
	fullnamear text NULL,
	fullnameen text NULL,
	alternativemobilecountrycode text NULL,
	alternativemobileno text NULL,
	apartment text NULL,
	buildingno text NULL,
	city text NULL,
	companynamear text NULL,
	companynameen text NULL,
	country text NULL,
	customerindividual_passportexpirydate text NULL,
	customerindividual_passportno text NULL,
	dldparticipantno text NULL,
	dateofbirth text NULL,
	eidexpirydate text NULL,
	eidissuancedate text NULL,
	email text NULL,
	emiratesid text NULL,
	landline text NULL,
	mobile text NULL,
	mobilecountrycode text NULL,
	nationality text NULL,
	operatorname text NULL,
	ownershippercentage text NULL,
	passportexpirydate text NULL,
	passportissuancedate text NULL,
	passportno text NULL,
	phone text NULL,
	"position" text NULL,
	postalcode text NULL,
	rejectedreason text NULL,
	representativealtmobile text NULL,
	representativealtmobilecountrycode text NULL,
	representativeemail text NULL,
	representativefullnamear text NULL,
	representativefullnameen text NULL,
	representativemobile text NULL,
	representativemobilecountrycode text NULL,
	residencevisanumber text NULL,
	status text NULL,
	street text NULL,
	tradelicence text NULL,
	tradelicenceexpirydate text NULL,
	tradelicenceissuer text NULL,
	"type" text NULL,
	visaexpirydate text NULL,
	visaissuancedate text NULL,
	isfirsttimebuyer text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_fullnamear ev.vector NULL,
	embed_fullnameen ev.vector NULL,
	embed_city ev.vector NULL,
	embed_companynamear ev.vector NULL,
	embed_companynameen ev.vector NULL,
	embed_country ev.vector NULL,
	embed_nationality ev.vector NULL,
	embed_operatorname ev.vector NULL,
	embed_position ev.vector NULL,
	embed_representativefullnamear ev.vector NULL,
	embed_representativefullnameen ev.vector NULL,
	embed_street ev.vector NULL"""
        },
    },

    "customerrequesttrackers": {
        "domain": "crm",
        "columns": {"""
	id int4 NULL,
	actioncount text NULL,
	customerid text NULL,
	isactive text NULL,
	lable text NULL,
	orders text NULL,
	roleid text NULL,
	rolename text NULL,
	status text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_label ev.vector NULL,
	embed_rolename ev.vector NULL,
	embed_status ev.vector NULL"""
        },      
    },

    "customers_deals": {
        "domain": "crm_sales",
        "columns": {
            """customer_id": "int4"
            
	id int4 NULL,
	"name" text NULL,
	directorid text NULL,
	projectname text NULL,
	salesoffer text NULL,
	accountmanagername text NULL,
	agentid text NULL,
	unitid text NULL,
	attachecidocuments text NULL,
	bookingdate text NULL,
	bookingtype text NULL,
	brnnumber text NULL,
	cancellationreason text NULL,
	cancelledby text NULL,
	cancelleddate text NULL,
	contactname text NULL,
	dasholding text NULL,
	eciid text NULL,
	agentfreelancername text NULL,
	originalprice text NULL,
	paymentmodel text NULL,
	salesleadsource text NULL,
	shareddealowner text NULL,
	stage text NULL,
	status text NULL,
	unitnumber text NULL,
	rsvsenttoclient text NULL,
	rsvsenttoclientdate text NULL,
	rsvsignedbyclient text NULL,
	spasentforsignature text NULL,
	spasignedbyclient text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_projectname ev.vector NULL,
	embed_accountmanagername ev.vector NULL,
	embed_contactname ev.vector NULL,
	embed_agentfreelancername ev.vector NULL,
	creationdate timestamptz(6) NULL
            """, 
            
        },

    },

    "deals": {
        "domain": "deals",
        "columns": {"""
	id int4 NULL,
	"name" text NULL,
	directorid text NULL,
	projectname text NULL,
	salesoffer text NULL,
	accountmanagername text NULL,
	agentid text NULL,
	unitid text NULL,
	attachecidocuments text NULL,
	bookingdate text NULL,
	bookingtype text NULL,
	brnnumber text NULL,
	cancellationreason text NULL,
	cancelledby text NULL,
	cancelleddate text NULL,
	contactname text NULL,
	dasholding text NULL,
	eciid text NULL,
	agentfreelancername text NULL,
	originalprice text NULL,
	paymentmodel text NULL,
	salesleadsource text NULL,
	shareddealowner text NULL,
	stage text NULL,
	status text NULL,
	unitnumber text NULL,
	rsvsenttoclient text NULL,
	rsvsenttoclientdate text NULL,
	rsvsignedbyclient text NULL,
	spasentforsignature text NULL,
	spasignedbyclient text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_projectname ev.vector NULL,
	embed_accountmanagername ev.vector NULL,
	embed_contactname ev.vector NULL,
	embed_agentfreelancername ev.vector NULL,
	creationdate timestamptz(6) NULL"""
        },
        
    },

    "deals_units": {
    "domain": "deals",
    "columns": {
      
        """"deal_id": "int4"
        
	id int4 NULL,
	"name" text NULL,
	"number" text NULL,
	buildingid text NULL,
	unitclusterid text NULL,
	availabilitystatus text NULL,
	baths text NULL,
	bedroom text NULL,
	floor text NULL,
	furnished text NULL,
	kitchen text NULL,
	layouthashcode text NULL,
	parking text NULL,
	plotnumber text NULL,
	area text NULL,
	price text NULL,
	pricepersqft text NULL,
	currency text NULL,
	description text NULL,
	"type" text NULL,
	"view" text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_shortname ev.vector NULL,
	embed_availabilitystatus ev.vector NULL,
	embed_bedroom ev.vector NULL,
	embed_furnished ev.vector NULL,
	embed_kitchen ev.vector NULL,
	embed_parking ev.vector NULL,
	embed_description ev.vector NULL,
	embed_type ev.vector NULL,
	embed_view ev.vector NULL
        """,
        
    },
    },

    "deals_projects": {
    "domain": "deals",
    "columns": {
        """"deal_id": "int4"
        
	id int4 NULL,
	"name" text NULL,
	shortname text NULL,
	developerid int4 NULL,
	address text NULL,
	"location" text NULL,
	status text NULL,
	accountnumber text NULL,
	bankaddress text NULL,
	bankbranch text NULL,
	bankname text NULL,
	adminfee text NULL,
	corporateaccountname text NULL,
	corporateaccountnumber text NULL,
	corporatebankaddress text NULL,
	corporatebankbranch text NULL,
	corporatebankname text NULL,
	corporateibannumber text NULL,
	escrowaccountname text NULL,
	ibannumber text NULL,
	currency text NULL,
	isavailabiletoportal text NULL,
	latitude text NULL,
	longitude text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_name ev.vector NULL,
	embed_shortname ev.vector NULL,
	embed_location ev.vector NULL,
	embed_bankaddress ev.vector NULL,
	embed_bankbranch ev.vector NULL,
	embed_bankname ev.vector NULL,
	embed_corporateaccountname ev.vector NULL,
	embed_corporatebankaddress ev.vector NULL,
	embed_corporatebankbranch ev.vector NULL,
	embed_corporatebankname ev.vector NULL,
	embed_escrowaccountname ev.vector NULL,
	embed_isavailabiletoportal ev.vector NULL,
	embed_latitude ev.vector NULL,
	embed_longitude ev.vector NULL,
	embed_address ev.vector NULL""",
    },

},

    "deals_customers":{
        "domain": "deals",
    "columns": {
      
        """"deal_id": "int4",
        
	id int4 NULL,
	fullnamear text NULL,
	fullnameen text NULL,
	alternativemobilecountrycode text NULL,
	alternativemobileno text NULL,
	apartment text NULL,
	buildingno text NULL,
	city text NULL,
	companynamear text NULL,
	companynameen text NULL,
	country text NULL,
	customerindividual_passportexpirydate text NULL,
	customerindividual_passportno text NULL,
	dldparticipantno text NULL,
	dateofbirth text NULL,
	eidexpirydate text NULL,
	eidissuancedate text NULL,
	email text NULL,
	emiratesid text NULL,
	landline text NULL,
	mobile text NULL,
	mobilecountrycode text NULL,
	nationality text NULL,
	operatorname text NULL,
	ownershippercentage text NULL,
	passportexpirydate text NULL,
	passportissuancedate text NULL,
	passportno text NULL,
	phone text NULL,
	"position" text NULL,
	postalcode text NULL,
	rejectedreason text NULL,
	representativealtmobile text NULL,
	representativealtmobilecountrycode text NULL,
	representativeemail text NULL,
	representativefullnamear text NULL,
	representativefullnameen text NULL,
	representativemobile text NULL,
	representativemobilecountrycode text NULL,
	residencevisanumber text NULL,
	status text NULL,
	street text NULL,
	tradelicence text NULL,
	tradelicenceexpirydate text NULL,
	tradelicenceissuer text NULL,
	"type" text NULL,
	visaexpirydate text NULL,
	visaissuancedate text NULL,
	isfirsttimebuyer text NULL,
	row_txt text NULL,
	embedding ev.vector NULL,
	embed_fullnamear ev.vector NULL,
	embed_fullnameen ev.vector NULL,
	embed_city ev.vector NULL,
	embed_companynamear ev.vector NULL,
	embed_companynameen ev.vector NULL,
	embed_country ev.vector NULL,
	embed_nationality ev.vector NULL,
	embed_operatorname ev.vector NULL,
	embed_position ev.vector NULL,
	embed_representativefullnamear ev.vector NULL,
	embed_representativefullnameen ev.vector NULL,
	embed_street ev.vector NULL
        """
        
        
    },
    },

    "deals_directors": {
        "domain": "organization",
        "columns": {
            "deal_id": "int4",
            "director_sap": "text",
            "director_id": "int4",
            "director_name": "text",
            "director_email": "text",
            "director_mobile": "text",
            "director_empcode": "text",
            "director_nationality": "text",
            "director_address": "text",
            "director_role": "text",
            "director_position": "text",
            "director_department": "text",
            "director_section": "text",
            "director_reportingmanagerid": "text",
            "director_employmentdate": "text",
            "director_portalstatus": "text",
            "director_status": "text",
            "director_row_txt": "text",
            "director_embedding": "ev.vector",
            "director_embed_name": "ev.vector",
            "director_embed_nationality": "ev.vector",
            "director_embed_address": "ev.vector",
            "director_embed_role": "ev.vector",
            "director_embed_position": "ev.vector",
            "director_embed_department": "ev.vector",
            "director_embed_section": "ev.vector",
            "hos_id": "int4",
            "hos_name": "text",
            "hos_email": "text",
            "hos_mobile": "text",
            "hos_empcode": "text",
            "hos_nationality": "text",
            "hos_address": "text",
            "hos_role": "text",
            "hos_position": "text",
            "hos_department": "text",
            "hos_section": "text",
            "hos_reportingmanagerid": "text",
            "hos_employmentdate": "text",
            "hos_portalstatus": "text",
            "hos_status": "text",
            "hos_row_txt": "text",
            "hos_embedding": "ev.vector",
            "hos_embed_name": "ev.vector",
            "hos_embed_nationality": "ev.vector",
            "hos_embed_address": "ev.vector",
            "hos_embed_role": "ev.vector",
            "hos_embed_position": "ev.vector",
            "hos_embed_department": "ev.vector",
            "hos_embed_section": "ev.vector"
        },

    },

    "deals_agents": {
            "domain": "organization",
        "columns": {
            "deal_id": "int4",
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
             "teamid": "text",
            "sap": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    } ,

    "bookings": {
            "domain": "sales",
        "columns":{"""
	id int4 NOT NULL,
	unitid int4 NULL,
	originalprice float8 NULL,
	agreedprice float8 NULL,
	transferredtodeal bool NULL,
	customerid int4 NULL,
	projectid int4 NULL,
	stage text NULL,
	agentid int4 NULL,
	managerid int4 NULL,
	headofsalesid int4 NULL,
	csoid int4 NULL,
	layout text NULL,
	brokerid int4 NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	paymentlinkid int4 NULL,
	bookingreferenceid text NULL,
	draftedamount float8 NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
        },
    } ,

    "paymentLinks": {
            "domain": "sales",
        "columns":{"""

	id int4 NOT NULL,
	amount float8 NULL,
	currency text NULL,
	paymenttype text NULL,
	paymenturl text NULL,
	status text NULL,
	expirydate text NULL,
	refno text NULL,
	paymentlinkreferenceid text NULL,
	projectid int4 NULL,
	agentid int4 NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	issplited bool NULL,
	remainingamount float8 NULL,
	servicechargepercentage float8 NULL,
	embed_paymenttype ev.vector NULL,
	embed_status ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,
	CONSTRAINT paymentlinks_pkey PRIMARY KEY (id)
"""
    } ,
},

    "payments": {
                "domain": "payments",
            "columns":{"""
        id int4 NOT NULL,
        paymentreceiptdetailsname text NULL,
        status text NULL,
        amount float8 NULL,
        account text NULL,
        paymentmethod text NULL,
        dateofreceipt text NULL,
        chqddttnumber text NULL,
        dateoftransaction text NULL,
        chequedepositdate text NULL,
        chequereturneddate text NULL,
        dealid int4 NULL,
        receivedbyevdate text NULL,
        transferredtodeveloperdate text NULL,
        receiveddate text NULL,
        popreference int4 NULL,
        isformrequested bool NULL,
        isloading bool NULL,
        currency text NULL,
        customerid int4 NULL,
        paymentstatus text NULL,
        createdby text NULL,
        creationdate text NULL,
        isdeleted bool NULL,
        embed_paymentreceiptdetailsname ev.vector NULL,
        embed_status ev.vector NULL,
        embed_account ev.vector NULL,
        embed_paymentmethod ev.vector NULL,
        embed_paymentstatus ev.vector NULL,
        row_text text NULL,
        embedding ev.vector NULL,"""
    }},
    
    "installmentplans": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	"name" text NULL,
	priority int4 NULL,
	percentage float8 NULL,
	amount float8 NULL,
	duedate text NULL,
	paymentdate text NULL,
	settled bool NULL,
	status text NULL,
	paidamount float8 NULL,
	remainingamount float8 NULL,
	dealid int4 NULL,
	accounttype text NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	embed_name ev.vector NULL,
	embed_status ev.vector NULL,
	embed_accounttype ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "instalmentadjusted": {
                "domain": "payments",
            "columns":{"""id int4 NOT NULL,
	instalmenttype text NULL,
	amount float8 NULL,
	paymentmethod text NULL,
	paymentid int4 NULL,
	instalmentplanid int4 NULL,
	accounttype text NULL,
	currency text NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	embed_instalmenttype ev.vector NULL,
	embed_paymentmethod ev.vector NULL,
	embed_accounttype ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "onlinepaymenttransactions": {
                "domain": "payments",
            "columns":{
       """id int4 NOT NULL,
	transactionnumber text NULL,
	amount float8 NULL,
	status text NULL,
	paymentlink text NULL,
	creationdatetime text NULL,
	businessentityid int4 NULL,
	businessentitytype int4 NULL,
	embed_status ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "paymentplandetails": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	salesproposalid int4 NULL,
	evinstalment text NULL,
	duedate text NULL,
	amount float8 NULL,
	percentage float8 NULL,
	paymenttermitemid int4 NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	embed_evinstalment ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "paymentsplits": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	paymentlinkid text NULL,
	amount float8 NULL,
	status text NULL,
	isfullpaymentamount bool NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	embed_status ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "paymentterms": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	ptid text NULL,
	adminfee float8 NULL,
	dldfee float8 NULL,
	"name" text NULL,
	exchangerate float8 NULL,
	status bool NULL,
	currency text NULL,
	bedtype text NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	embed_name ev.vector NULL,
	embed_status ev.vector NULL,
	embed_bedtype ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "paymenttermitems": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	"name" text NULL,
	gap int4 NULL,
	percentage float8 NULL,
	duedate text NULL,
	paymenttermid int4 NULL,
	milestonegaptype text NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	embed_name ev.vector NULL,
	embed_milestonegaptype ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "projectpaymentplans": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	projectid int4 NULL,
	paymenttermid int4 NULL,
	createdby text NULL,
	creationdate text NULL,
	isdeleted bool NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "projectpaymentterms": {
                "domain": "payments",
            "columns":{"""
	id int4 NOT NULL,
	layout text NULL,
	projectid int4 NULL,
	minimumamount float8 NULL,
	embed_layout ev.vector NULL,
	row_text text NULL,
	embedding ev.vector NULL,"""
    }},
    
    "projectpayment": {
                "domain": "payments viwe (not yet) projectpaymentterms, projectpaymentplans ",
            "columns":{
        "Id": "int",
        "ProjectId": "int",
        "Layout": "text",
        "MinimumAmount": "decimal",
        "projectid": "int4",
        "projectname": "text",
        "projectshortname": "text",
        "projectdeveloperid": "int4",
        "projectaddress": "text",
        "projectlocation": "text",
        "projectstatus": "text",
        "projectaccountnumber": "text",
        "projectbankaddress": "text",
        "projectbankbranch": "text",
        "projectbankname": "text",
        "projectadminfee": "text",
        "projectcorporateaccountname": "text",
        "projectcorporateaccountnumber": "text",
        "projectcorporatebankaddress": "text",
        "projectcorporatebankbranch": "text",
        "projectcorporatebankname": "text",
        "projectcorporateibannumber": "text",
        "projectescrowaccountname": "text",
        "projectibannumber": "text",
        "projectcurrency": "text",
        "projectisavailabiletoportal": "text",
        "projectlatitude": "text",
        "projectlongitude": "text",
        "embed_projectname": "ev.vector",
        "embed_projectshortname": "ev.vector",
        "embed_projectlocation": "ev.vector",
        "embed_projectbankaddress": "ev.vector",
        "embed_projectbankbranch": "ev.vector",
        "embed_projectbankname": "ev.vector",
        "embed_projectcorporateaccountname": "ev.vector",
        "embed_projectcorporatebankaddress": "ev.vector",
        "embed_projectcorporatebankbranch": "ev.vector",
        "embed_projectcorporatebankname": "ev.vector",
        "embed_projectescrowaccountname": "ev.vector",
        "embed_projectisavailabiletoportal": "ev.vector",
        "embed_projectlatitude": "ev.vector",
        "embed_projectlongitude": "ev.vector",
        "CreatedBy": "text",
        "CreationDate": "text",
        "IsDeleted": "bool", 
        "row_txt": "text",
        "embedding": "ev.vector"
    }}

}


# WORD/PARTIAL SEARCH authorization (by domain → table → columns)
word_search_list: Dict[str, Dict[str, List[str]]] = {
    
        "developers": ["portalaccesstype"],
        "projects":   [ "status", "isavailabiletoportal"],
        "buildings":  ["availabilitystatus", "availab", "bedroom", "currency", "status", "isavailabiletoportal"],
        "units":      ["availabilitystatus",  "currency", "baths", "bedroom" , "furnished", "kitchen",   "type",],
        
        "employees": ["portalstatus", "status",  ],
        "directors_employees": ["director_portalstatus",  "director_status", "hos_portalstatus",    "hos_status"],
        "hos_employee":["portalstatus",    "status" ],
        "brokers":   [ "stage", "city", "country"],
        "teams":     [ ],
        "agents_employee":  ["portalstatus",   "status" ],
       
        "customers": [ "country", "city",  "status"],
        "customerrequesttrackers": ["lable", "status"],
        "customers_deals" : [ "name",  "stage", "status",  "country", "city",],


        "deals": [ "name", "type", "stage",  "status", "city", "country"],
        "deals_customers": [ "country", "city", "status"],
        "deals_units": [ "stage", "status", "salesleadsource", "availabilitystatus", "bedroom","furnished","kitchen","parking", "currency","type",  "availability", "bookingtype",],
        "deals_projects": [ "salesleadsource", "stage", "status", "isavailabiletoportal", ],     
        "deals_directors": ["director_portalstatus",   "director_status", "hos_portalstatus",   "hos_status"],
        "deals_agents":  ["portalstatus",  "status" ],

        "bookings": ["Stage", "layout", "TransferredToDeal",  ],

        "paymentlinks": ["paymenttype", "status", "currency" ],
        "paymentsplits":[ "status",], 
        "payments":["paymentreceiptdetailsname", "status", "account", "paymentmethod", 
                    "chqddttnumber",  "currency", "paymentstatus",   ], 

        "paymentplandetails":[], 
        "onlinepaymenttransactions":["status"], 
        "installmentplans":["name", "status", "accounttype", ], 
        "instalmentadjusted":["instalmenttype", "paymentmethod", "accounttype", ],
        "paymenttermitems":["name", "milestonegaptype", ], 
        "paymentterms":["name", "bedtype", "status", "currency"], 
        "projectpaymentplans":[], 
        "projectpaymentterms":["layout", ],
}


operation_search_list : Dict[str, Dict[str, List[str]]] = {
    "developers": ["id", "phone", "portalaccesstype", "registrationnumber"],
    "projects":["id","developerid", "accountnumber", "adminfee", "corporateaccountnumber", 
                "corporateibannumber", "ibannumber",  "latitude", "longitude" ],
    "buildings": ["id", "developerid", "projectid", "accountnumber", "ibannumber", "paymenttermid", "latitude", "longitude" ],
    "units": ["id", "number", "buildingid", "unitclusterid", "baths", "floor", "layouthashcode","plotnumber",
                "area", "price", "pricepersqft", ],

    
    "employees": ["id", "mobile", "empcode", "reportingmanagerid",  "email",  ],
    "directors_employees": ["director_id", "director_mobile", "director_empcode", "director_reportingmanagerid", 
                           "director_sap",   "director_email", "hos_email",
                            "hos_id", "hos_mobile", "hos_empcode", "hos_reportingmanagerid", ],
    "hos_employee": ["id", "mobile", "empcode", "reportingmanagerid", "email", ],
    "brokers": ["id", "phone","zipcode", "emiratesid", "brokeragecompanyid",  "email",
                "passportnumber", "representativeemail", "representativemobile",
                "representativename", "tradelicensenumber", "userssoid",],
    "agents_employee" :["id", "mobile", "empcode", "reportingmanagerid", "teamid", "sap",  "email"],
    "teams": [],
   

    "customers": ["id", "mobile","mobilecountrycode","alternativemobileno","alternativemobilecountrycode", "email", "street", 
                "landline", "phone", "apartment","buildingno","postalcode" , "ownershippercentage"],
    "customerrequesttrackers": ["id", "customerid", "actioncount", "isactive", "roleid", "order"],
    "customers_deals" : [  "customer_id", "id", "directorid", "agentid", "unitid",   "street",],
    

    "deals": ["id", "directorid", "agentid", "unitid", ], 
    "deals_units": ["deal_id",  "directorid", "agentid", "id", "buildingid",  "unitclusterid", "price_range",
                    "area", "price",  "pricepersqft",  "number","baths","floor", "salesoffer", "paymentmodel", "unitnumber",  ],
    "deals_projects": [  "id",  "directorid",  "agentid",  "unitid",  "bookingtype", "stage",
                        "status", "originalprice",  "deal_id",  "latitude", "longitude" ],
    
    "deals_customers": ["deal_id","id", "mobile","mobilecountrycode","alternativemobileno","alternativemobilecountrycode",  "email",  "street",
                        "landline", "phone", "apartment","buildingno","postalcode" , "ownershippercentage"],

    "deals_agents" :["deal_id", "id", "mobile", "empcode", "reportingmanagerid",  "teamid",   "email", "sap" ],
    "deals_directors": ["deal_id","director_id", "director_mobile", "director_empcode", "director_reportingmanagerid", 
                            "director_sap",   "director_email",  "hos_email",
                            "hos_id", "hos_mobile", "hos_empcode", "hos_reportingmanagerid", ],


    "bookings": ["id", "unitid",  "originalprice", "agreedprice", "customerid",
										"projectid",  "agentid",  "managerid", "headofsalesid", "csoid",
										"brokerid",  "createdby",  "isdeleted", "paymentlinkid", "bookingreferenceid", "draftedamount"],
    "paymentlinks": ["id", "amount", "payment_url", "ref_no",  "payment_link_reference_id",
                     "project_id", "agent_id", "created_by",  "is_deleted",  "is_splited", "remaining_amount", "service_charge_percentage"],
    "paymentsplits":["id", "PaymentLinkId", "amount", "isfullpaymentamount", "createdby","isdeleted", ], 
    "payments":["id", "amount", "dealid", "popreference","isformrequested", "isloading","customerid","createdby","isdeleted",  ],  
        "paymentplandetails":["id", "salesproposalid", "paymenttermitemid", "amount", "percentage" ,"createdby","isdeleted", ], 
        "onlinepaymenttransactions":["id", "businessentityid", "businessentitytype",   "amount", "transactionnumber"], 
        "installmentplans":["id", "priority", "percentage", "amount",  "settled", "paidamount", "remainingamount", "dealid",  "createdby","isdeleted", ], 
        "instalmentadjusted":["id", "amount",   "paymentid", "instalmentplanid", "currency",  "createdby","isdeleted", ],
        "paymenttermitems":["id",  "gap", "percentage",   "paymenttermid"], 
        "paymentterms":["id", "ptid", "adminfee", "dldfee", "exchangerate",   "createdby","isdeleted", ], 
        "projectpaymentplans":["id", "projectid", "paymenttermid", "createdby","isdeleted", ], 
        "projectpaymentterms":["id", "projectid", "minimumamount",   ],
  }   

# SEMANTIC SEARCH columns (MUST align to available embed_* columns)
semantic_search_list: Dict[str, Dict[str, List[str]]] = {
    
        "developers": ["name", "operatorname"],  # only columns with embeddings
        "projects": [  "name", "shortname", "location", "bankaddress", "bankbranch", "bankname",
            "corporateaccountname", "corporatebankaddress", "corporatebankbranch",
            "corporatebankname", "escrowaccountname",  "address" ],
        "units": [ "name", "shortname",   "description",  "view",  ],
        "buildings": [ "name", "shortname", "location", "bankaddress", "bankbranch",
            "bankname", "escrowaccountname","address"  ],
               
        
        "employees": ["name", "nationality", "address", "role", "position", "department", "section"],
        "hos_employee": ["name", "nationality", "address", "role", "position", "department", "section"],
        "directors_employees": ["director_name", "director_nationality", "director_address", "director_role", "director_position", "director_department", "director_section",
                                "hos_name", "hos_nationality", "hos_address", "hos_role", "hos_position",  "hos_department", "hos_section"],
        "teams": ["name"],
        "agents_employee":["name", "nationality", "address", "role", "position", "department", "section"],
        "brokers": ["name", "nationality", "address", "evrepresentativename" ],
        
        
        "customers": ["fullnameen", "fullnamear", "nationality",  "companynamear", "companynameen", "operatorname", "position",],
        "customerrequesttrackers": ["rolename"],
        "customers_deals": [  "fullnameen",  "fullnamear",  "nationality", "companynamear",  "companynameen",  "operatorname",
                            "position",  "deal_name",  "projectname", "accountmanagername",  ],

        "deals": ["address", "role", "position", "section", "department", "nationality", ],
        "deals_units": [   "deal_name",  "projectname" , "paymentmodel", "contactname",  "agentfreelancername",
                         "accountmanagername",  "unit_name",   "description",  "unit_view",  "project",  "booking",   ],

        "deals_projects":[  "name",   "projectname",  "accountmanagername", "contactname", "agentfreelancername", "project_name",
                          "project_shortname",  "project_location",   "bankaddress", "bankbranch",  "bankname", "corporateaccountname",
                         "corporatebankaddress", "corporatebankbranch", "corporatebankname",  "escrowaccountname",  ],

        "deals_directors": ["director_name", "director_nationality", "director_address", "director_role", 
                                "director_position", "director_department", "director_section",
                                "hos_name", "hos_nationality", "hos_address", "hos_role", "hos_position",
                                  "hos_department", "hos_section"],

        "deals_agents":["name", "nationality", "address", "role", "position", "department", "section"],
        "deals_customers" :["fullnameen",  "fullnamear",  "nationality", "companynamear",  "companynameen",  "operatorname",
                            "position",  "deal_name",  "projectname", "accountmanagername", ],

        "bookings" : [],
        "paymentlinks": [],
        "paymentsplits":[], 
        "payments":[], 
        "paymentplandetails":["evinstalment"], 
        "onlinepaymenttransactions":[], 
        "installmentplans":[], 
        "instalmentadjusted":[],
        "paymenttermitems":[], 
        "paymentterms":[], 
        "projectpaymentplans":[], 
        "projectpaymentterms":[],

}

datetime_search_list : Dict[str, Dict[str, List[str]]] = {
    
        "developers": [ ] ,
        "projects": [ ],
        "units": [   ],
        "buildings": [   ],
               
        
        "employees": [ "employmentdate", ],
        "hos_employee": [  "employmentdate",],
        "directors_employees": [  "director_employmentdate","hos_employmentdate", ],
        "teams": [ ],
        "agents_employee":[  "employmentdate",],
        "brokers": [  "passportissueddate" , "passportexpirydate", ],
        
        
        "customers": [ ],
        "customerrequesttrackers": [ ],
        "customers_deals": [    ],

        "deals": [  ],
        "deals_units": [   "bookingdate",   ],

        "deals_projects":[ "bookingdate", ],

        "deals_directors": ["director_employmentdate", "hos_employmentdate", ],

        "deals_agents":[ "employmentdate",],
        "deals_customers" :[    ],

        "bookings" : ["creationdate",],
        "paymentlinks": ["expiry_date", "creation_date",],
        "paymentsplits":[ "creationdate",], 
        "payments":["dateofreceipt", "dateoftransaction", "chequedepositdate", "chequereturneddate",
                    "receivedbyevdate", "transferredtodeveloperdate", "receiveddate", "creationdate", ], 
        "paymentplandetails":["duedate", "creationdate", ], 
        "onlinepaymenttransactions":["creationdatetime", ], 
        "installmentplans":["duedate", "paymentdate",  "creationdate",], 
        "instalmentadjusted":["creationdate",],
        "paymenttermitems":["duedate"], 
        "paymentterms":[ "creationdate",], 
        "projectpaymentplans":[ "creationdate",], 
        "projectpaymentterms":[],

}
