
# main/static.py
from typing import Any, Dict, List


# ============================================================
# Structured SCHEMA metadata (authoritative)
# ============================================================
# Each table: columns (name->type), id_columns, embedding_columns, relations

domain = [ [],
           [ "developers", "projects", "buildings", "units" ],
           [ "employees", "directors_employees", "hos_employee", "teams", "agents_employee" ],
           [ "customers","customerrequesttrackers",  "customers_deals", ],
           [ "deals", "deals_units", "deals_projects", "deals_customers", "deals_directors", "deals_agents"  ], 
           ["bookings", "paymentlinks", "projects", "buildings", "units", "employees", "agents_employee", "customers", "brokers" ],
           [ "paymentsplits", "payments", "paymentplandetails", "paymentlinks", "onlinepaymenttransactions", "installmentplans", "instalmentadjusted",
              "paymenttermitems", "paymentterms", "projectpaymentplans", "projectpaymentterms" ]]


SCHEMA: Dict[str, Dict[str, Any]] = {
    "developers": {
        "domain": "property",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "operatorname": "text",
            "phone": "text",
            "portalaccesstype": "text",
            "registrationnumber": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_operatorname": "ev.vector",
        }
    },

    "projects": {
        "domain": "property",
        "columns": {
            "id": "int4",
            "name": "text",
            "shortname": "text",
            "developerid": "int4",
            "address": "text",
            "location": "text",
            "status": "text",
            "accountnumber": "text",
            "bankaddress": "text",
            "bankbranch": "text",
            "bankname": "text",
            "adminfee": "text",
            "corporateaccountname": "text",
            "corporateaccountnumber": "text",
            "corporatebankaddress": "text",
            "corporatebankbranch": "text",
            "corporatebankname": "text",
            "corporateibannumber": "text",
            "escrowaccountname": "text",
            "ibannumber": "text",
            "currency": "text",
            "isavailabiletoportal": "text",
            "latitude": "text",
            "longitude": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_shortname": "ev.vector",
            "embed_location": "ev.vector",
            "embed_address": "ev.vector",
            "embed_bankaddress": "ev.vector",
            "embed_bankbranch": "ev.vector",
            "embed_bankname": "ev.vector",
            "embed_corporateaccountname": "ev.vector",
            "embed_corporatebankaddress": "ev.vector",
            "embed_corporatebankbranch": "ev.vector",
            "embed_corporatebankname": "ev.vector",
            "embed_escrowaccountname": "ev.vector",
            "embed_isavailabiletoportal": "ev.vector",
            "embed_latitude": "ev.vector",
            "embed_longitude": "ev.vector",
        },
        
    },

    "buildings": {
        "domain": "property",
        "columns": {
            "id": "int4",
            "name": "text",
            "shortname": "text",
            "developerid": "int4",
            "projectid": "int4",
            "address": "text",
            "location": "text",
            "status": "text",
            "accountnumber": "text",
            "bankaddress": "text",
            "bankbranch": "text",
            "bankname": "text",
            "escrowaccountname": "text",
            "ibannumber": "text",
            "currency": "text",
            "paymenttermid": "int4",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_shortname": "ev.vector",
            "embed_location": "ev.vector",
            "embed_address": "ev.vector",
            "embed_bankaddress": "ev.vector",
            "embed_bankbranch": "ev.vector",
            "embed_bankname": "ev.vector",
            "embed_escrowaccountname": "ev.vector",
        },

    },

    "units": {
        "domain": "property",
        "columns": {
            "id": "int4",
            "name": "text",
            "number": "text",
            "buildingid": "text",  # NOTE: stored as text; cast to int where needed
            "unitclusterid": "text",
            "availabilitystatus": "text",
            "baths": "text",
            "bedroom": "text",
            "floor": "text",
            "furnished": "text",
            "kitchen": "text",
            "layouthashcode": "text",
            "parking": "text",
            "plotnumber": "text",
            "area": "text",
            "price": "text",
            "pricepersqft": "text",
            "currency": "text",
            "description": "text",
            "type": "text",
            "view": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_shortname": "ev.vector",
            "embed_availabilitystatus": "ev.vector",
            "embed_bedroom": "ev.vector",
            "embed_furnished": "ev.vector",
            "embed_kitchen": "ev.vector",
            "embed_parking": "ev.vector",
            "embed_description": "ev.vector",
            "embed_type": "ev.vector",
            "embed_view": "ev.vector",
        },
        
    },

    "employees": {
        "domain": "organization",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    },
    
    "directors_employees": {
        "domain": "organization",
        "columns": {
            "director_sap": "text",
            "director_id": "int4",
            "director_name": "text",
            "director_email": "text",
            "director_mobile": "text",
            "director_empcode": "text",
            "director_nationality": "text",
            "director_address": "text",
            "director_role": "text",
            "director_position": "text",
            "director_department": "text",
            "director_section": "text",
            "director_reportingmanagerid": "text",
            "director_employmentdate": "text",
            "director_portalstatus": "text",
            "director_status": "text",
            "director_row_txt": "text",
            "director_embedding": "ev.vector",
            "director_embed_name": "ev.vector",
            "director_embed_nationality": "ev.vector",
            "director_embed_address": "ev.vector",
            "director_embed_role": "ev.vector",
            "director_embed_position": "ev.vector",
            "director_embed_department": "ev.vector",
            "director_embed_section": "ev.vector",
            "hos_id": "int4",
            "hos_name": "text",
            "hos_email": "text",
            "hos_mobile": "text",
            "hos_empcode": "text",
            "hos_nationality": "text",
            "hos_address": "text",
            "hos_role": "text",
            "hos_position": "text",
            "hos_department": "text",
            "hos_section": "text",
            "hos_reportingmanagerid": "text",
            "hos_employmentdate": "text",
            "hos_portalstatus": "text",
            "hos_status": "text",
            "hos_row_txt": "text",
            "hos_embedding": "ev.vector",
            "hos_embed_name": "ev.vector",
            "hos_embed_nationality": "ev.vector",
            "hos_embed_address": "ev.vector",
            "hos_embed_role": "ev.vector",
            "hos_embed_position": "ev.vector",
            "hos_embed_department": "ev.vector",
            "hos_embed_section": "ev.vector"
        },

    },

    "hos_employee":  {
        "domain": "organization",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    },

    "brokers": {
        "domain": "brokers-info",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "phone": "text",
            "nationality": "text",
            "address": "text",
            "city": "text",
            "country": "text",
            "zipcode": "text",
            "emiratesid": "text",
            "type": "text",
            "brokeragecompanyid": "text",
            "website": "text",
            "referred": "text",
            "evrepresentativename": "text",
            "stage": "text",
            "brn": "text",
            "orn": "text",
            "trn": "text",
            "passportexpirydate": "text",
            "passportissueddate": "text",
            "passportnumber": "text",
            "representativeemail": "text",
            "representativemobile": "text",
            "representativename": "text",
            "tradelicensenumber": "text",
            "userssoid": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_city": "ev.vector",
            "embed_country": "ev.vector",
            "embed_type": "ev.vector",
            "embed_stage": "ev.vector",
        },
        
    },

    "teams": {
        "domain": "organization",
        "columns": {
            "id": "int4",
            "name": "text",
            "directorid": "text",
            "sap": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
        },
    },

    "agents_employee": {
            "domain": "organization",
        "columns": {
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
             "teamid": "text",
            "sap": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    } ,
    
    "customers": {
        "domain": "crm",
        "columns": {
            "id": "int4",
            "fullnamear": "text",
            "fullnameen": "text",
            "email": "text",
            "mobile": "text",
            "mobilecountrycode": "text",
            "alternativemobileno": "text",
            "alternativemobilecountrycode": "text",
            "landline": "text",
            "phone": "text",
            "nationality": "text",
            "country": "text",
            "city": "text",
            "street": "text",
            "apartment": "text",
            "buildingno": "text",
            "postalcode": "text",
            "companynamear": "text",
            "companynameen": "text",
            "operatorname": "text",
            "position": "text",
            "ownershippercentage": "text",
            "type": "text",
            "status": "text",
            "isfirsttimebuyer": "text",
            "dateofbirth": "text",
            "emiratesid": "text",
            "eidissuancedate": "text",
            "eidexpirydate": "text",
            "passportno": "text",
            "passportissuancedate": "text",
            "passportexpirydate": "text",
            "visaissuancedate": "text",
            "visaexpirydate": "text",
            "residencevisanumber": "text",
            "tradelicence": "text",
            "tradelicenceissuer": "text",
            "tradelicenceexpirydate": "text",
            "dldparticipantno": "text",
            "representativefullnamear": "text",
            "representativefullnameen": "text",
            "representativeemail": "text",
            "representativemobile": "text",
            "representativemobilecountrycode": "text",
            "representativealtmobile": "text",
            "representativealtmobilecountrycode": "text",
            "rejectedreason": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_fullnamear": "ev.vector",

            "embed_fullnameen": "ev.vector",
            "embed_city": "ev.vector",
            "embed_companynamear": "ev.vector",
            "embed_companynameen": "ev.vector",
            "embed_country": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_operatorname": "ev.vector",
            "embed_position": "ev.vector",
            "embed_representativefullnamear": "ev.vector",
            "embed_representativefullnameen": "ev.vector",
            "embed_street": "ev.vector",
        },
    },

    "customerrequesttrackers": {
        "domain": "crm",
        "columns": {
            "id": "int4",
            "customerid": "int4",
            "actioncount": "text",
            "isactive": "text",
            "lable": "text",
            "order": "text",
            "roleid": "text",
            "rolename": "text",
            "status": "text",
            "embedding": "ev.vector",
            "embed_label": "ev.vector",
            "embed_rolename": "ev.vector",
            "embed_status": "ev.vector",
        },      
    },

    "customers_deals": {
        "domain": "crm_sales",
        "columns": {
            "customer_id": "int4", 
            
            "id": "int4",
            "directorid": "text",
            "agentid": "text",
            "unitid": "text",
            "name": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "section": "text",
            "status": "text",
            "stage": "text",
            "department": "text",
            "city": "text",
            "country": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            
"embed_name": "ev.vector",

"embed_projectname": "ev.vector",
"embed_accountmanagername": "ev.vector",
"embed_contactname": "ev.vector",
"embed_agentfreelancername": "ev.vector",
        },

    },

    "deals": {
        "domain": "deals",
        "columns": {
            "id": "int4",
            "directorid": "text",
            "agentid": "text",
            "unitid": "text",
            "name": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "section": "text",
            "status": "text",
            "stage": "text",
            "department": "text",
            "city": "text",
            "country": "text",
            "CreationDate": "TIMESTAMPTZ(6)",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_projectname": "ev.vector",
            "embed_accountmanagername": "ev.vector",
        },
        
    },

    "deals_units": {
    "domain": "deals",
    "columns": {
      
        "deal_id": "int4",
        
            "id": "int4",
            "name": "text",
            "number": "text",
            "buildingid": "text",  # NOTE: stored as text; cast to int where needed
            "unitclusterid": "text",
            "availabilitystatus": "text",
            "baths": "text",
            "bedroom": "text",
            "floor": "text",
            "furnished": "text",
            "kitchen": "text",
            "layouthashcode": "text",
            "parking": "text",
            "plotnumber": "text",
            "area": "text",
            "price": "text",
            "pricepersqft": "text",
            "currency": "text",
            "description": "text",
            "type": "text",
            "view": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_shortname": "ev.vector",
            "embed_availabilitystatus": "ev.vector",
            "embed_bedroom": "ev.vector",
            "embed_furnished": "ev.vector",
            "embed_kitchen": "ev.vector",
            "embed_parking": "ev.vector",
            "embed_description": "ev.vector",
            "embed_type": "ev.vector",
            "embed_view": "ev.vector",
    },
    },

    "deals_projects": {
    "domain": "deals",
    "columns": {
        "deal_id": "int4",
            "id": "int4",
            "name": "text",
            "shortname": "text",
            "developerid": "int4",
            "address": "text",
            "location": "text",
            "status": "text",
            "accountnumber": "text",
            "bankaddress": "text",
            "bankbranch": "text",
            "bankname": "text",
            "adminfee": "text",
            "corporateaccountname": "text",
            "corporateaccountnumber": "text",
            "corporatebankaddress": "text",
            "corporatebankbranch": "text",
            "corporatebankname": "text",
            "corporateibannumber": "text",
            "escrowaccountname": "text",
            "ibannumber": "text",
            "currency": "text",
            "isavailabiletoportal": "text",
            "latitude": "text",
            "longitude": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_shortname": "ev.vector",
            "embed_location": "ev.vector",
            "embed_bankaddress": "ev.vector",
            "embed_bankbranch": "ev.vector",
            "embed_bankname": "ev.vector",
            "embed_corporateaccountname": "ev.vector",
            "embed_corporatebankaddress": "ev.vector",
            "embed_corporatebankbranch": "ev.vector",
            "embed_corporatebankname": "ev.vector",
            "embed_escrowaccountname": "ev.vector",
            "embed_isavailabiletoportal": "ev.vector",
            "embed_latitude": "ev.vector",
            "embed_longitude": "ev.vector",
    },

},

    "deals_customers":{
        "domain": "deals",
    "columns": {
      
        "deal_id": "int4",
        
            "id": "int4",
            "fullnamear": "text",
            "fullnameen": "text",
            "email": "text",
            "mobile": "text",
            "mobilecountrycode": "text",
            "alternativemobileno": "text",
            "alternativemobilecountrycode": "text",
            "landline": "text",
            "phone": "text",
            "nationality": "text",
            "country": "text",
            "city": "text",
            "street": "text",
            "apartment": "text",
            "buildingno": "text",
            "postalcode": "text",
            "companynamear": "text",
            "companynameen": "text",
            "operatorname": "text",
            "position": "text",
            "ownershippercentage": "text",
            "type": "text",
            "status": "text",
            "isfirsttimebuyer": "text",
            "dateofbirth": "text",
            "emiratesid": "text",
            "eidissuancedate": "text",
            "eidexpirydate": "text",
            "passportno": "text",
            "passportissuancedate": "text",
            "passportexpirydate": "text",
            "visaissuancedate": "text",
            "visaexpirydate": "text",
            "residencevisanumber": "text",
            "tradelicence": "text",
            "tradelicenceissuer": "text",
            "tradelicenceexpirydate": "text",
            "dldparticipantno": "text",
            "representativefullnamear": "text",
            "representativefullnameen": "text",
            "representativeemail": "text",
            "representativemobile": "text",
            "representativemobilecountrycode": "text",
            "representativealtmobile": "text",
            "representativealtmobilecountrycode": "text",
            "rejectedreason": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_projectname": "ev.vector",
            "embed_accountmanagername": "ev.vector",
            "embed_contactname": "ev.vector",
            "embed_agentfreelancername": "ev.vector",
        
    },
    },

    "deals_directors": {
        "domain": "organization",
        "columns": {
            "deal_id": "int4",
            "director_sap": "text",
            "director_id": "int4",
            "director_name": "text",
            "director_email": "text",
            "director_mobile": "text",
            "director_empcode": "text",
            "director_nationality": "text",
            "director_address": "text",
            "director_role": "text",
            "director_position": "text",
            "director_department": "text",
            "director_section": "text",
            "director_reportingmanagerid": "text",
            "director_employmentdate": "text",
            "director_portalstatus": "text",
            "director_status": "text",
            "director_row_txt": "text",
            "director_embedding": "ev.vector",
            "director_embed_name": "ev.vector",
            "director_embed_nationality": "ev.vector",
            "director_embed_address": "ev.vector",
            "director_embed_role": "ev.vector",
            "director_embed_position": "ev.vector",
            "director_embed_department": "ev.vector",
            "director_embed_section": "ev.vector",
            "hos_id": "int4",
            "hos_name": "text",
            "hos_email": "text",
            "hos_mobile": "text",
            "hos_empcode": "text",
            "hos_nationality": "text",
            "hos_address": "text",
            "hos_role": "text",
            "hos_position": "text",
            "hos_department": "text",
            "hos_section": "text",
            "hos_reportingmanagerid": "text",
            "hos_employmentdate": "text",
            "hos_portalstatus": "text",
            "hos_status": "text",
            "hos_row_txt": "text",
            "hos_embedding": "ev.vector",
            "hos_embed_name": "ev.vector",
            "hos_embed_nationality": "ev.vector",
            "hos_embed_address": "ev.vector",
            "hos_embed_role": "ev.vector",
            "hos_embed_position": "ev.vector",
            "hos_embed_department": "ev.vector",
            "hos_embed_section": "ev.vector"
        },

    },

    "deals_agents": {
            "domain": "organization",
        "columns": {
            "deal_id": "int4",
            "id": "int4",
            "name": "text",
            "email": "text",
            "mobile": "text",
            "empcode": "text",
            "nationality": "text",
            "address": "text",
            "role": "text",
            "position": "text",
            "department": "text",
            "section": "text",
            "reportingmanagerid": "text",
            "employmentdate": "text",
            "portalstatus": "text",
            "status": "text",
             "teamid": "text",
            "sap": "text",
            "row_txt": "text",
            "embedding": "ev.vector",
            "embed_name": "ev.vector",
            "embed_nationality": "ev.vector",
            "embed_address": "ev.vector",
            "embed_role": "ev.vector",
            "embed_position": "ev.vector",
            "embed_department": "ev.vector",
            "embed_section": "ev.vector",
        },
        
    } ,

    "bookings": {
            "domain": "sales",
        "columns":{
            "Id": "int",
            "UnitId": "int",
            "OriginalPrice": "float",
            "AgreedPrice": "float",
            "TransferredToDeal": "bool",
             "CustomerId": "int",
            "ProjectId": "int",
            "Stage": "text",
            "AgentId": "int",
            "ManagerId": "int",
            "HeadOfSalesId": "int",
            "CSOId": "int",
            "Layout": "text",
            "BrokerId": "int",
            "CreatedBy": "text",
            "CreationDate": "text",
            "IsDeleted": "bool",
            "PaymentLinkId": "int",
            "BookingReferenceId": "text",
            "DraftedAmount": "float",
            "row_txt": "text",
            "embedding": "ev.vector",
        },
    } ,

    "paymentLinks": {
            "domain": "sales",
        "columns":{
            "Id": "int",
    "Amount": "float",
    "Currency": "text",
    "PaymentType": "text",
    "PaymentUrl": "text",
    "Status": "text",
    "ExpiryDate": "text",
    "RefNo": "text",
    "PaymentLinkReferenceId": "text",
    "ProjectId": "int",
    "AgentId": "int",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "IsSplited": "bool",
    "RemainingAmount": "float",
    "ServiceChargePercentage": "float"
    } ,
},


  "payments": {
            "domain": "payments",
        "columns":{
            
    "Id": "int",
    "PaymentReceiptDetailsName": "text",
    "Status": "text",
    "Amount": "int",
    "Account": "text",
    "PaymentMethod": "text",
    "DateOfReceipt": "text",
    "ChqDDTTNumber": "text",
    "DateOfTransaction": "text",
    "ChequeDepositDate": "text",
    "ChequeReturnedDate": "text",
    "DealId": "int",
    "ReceivedByEVDate": "text",
    "TransferredToDeveloperDate": "text",
    "ReceivedDate": "text",
    "POPReference": "int",
    "isFormRequested": "bool",
    "IsLoading": "bool",
    "Currency": "text",
    "CustomerId": "int",
    "PaymentStatus": "text",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_PaymentReceiptDetailsName": "ev.vector",
    "embed_Status": "ev.vector",
    "embed_Account": "ev.vector",
    "embed_PaymentMethod": "ev.vector",
    "embed_PaymentStatus": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "installmentplans": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "Name": "text",
    "Priority": "int",
    "Percentage": "int",
    "Amount": "int",
    "DueDate": "text",
    "PaymentDate": "text",
    "Settled": "bool",
    "Status": "text",
    "PaidAmount": "int",
    "RemainingAmount": "int",
    "DealId": "int",
    "AccountType": "text",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_Name": "ev.vector",
    "embed_Status": "ev.vector",
    "embed_AccountType": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "instalmentadjusted": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "InstalmentType": "text",
    "Amount": "int",
    "PaymentMethod": "text",
    "PaymentId": "int",
    "InstalmentPlanId": "int",
    "AccountType": "text",
    "Currency": "text",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_InstalmentType": "ev.vector",
    "embed_PaymentMethod": "ev.vector",
    "embed_AccountType": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "onlinepaymenttransactions": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "TransactionNumber": "int",
    "Amount": "int",
    "Status": "text",
    "PaymentLink": "text",
    "CreationDateTime": "text",
    "BusinessEntityId": "int",
    "BusinessEntityType": "int",
    "embed_status": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "paymentlinks": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "Amount": "int",
    "Currency": "text",
    "PaymentType": "text",
    "PaymentUrl": "text",
    "Status": "text",
    "ExpiryDate": "text",
    "RefNo": "text",
    "PaymentLinkReferenceId": "int",
    "ProjectId": "int",
    "AgentId": "int",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "IsSplited": "bool",
    "RemainingAmount": "int",
    "ServiceChargePercentage": "int",
    "embed_PaymentType": "ev.vector",
    "embed_Status": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "paymentplandetails": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "SalesProposalId": "int",
    "EVInstalment": "text",
    "DueDate": "text",
    "Amount": "int",
    "Percentage": "int",
    "PaymentTermItemId": "int",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_EVInstalment": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "paymentsplits": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "PaymentLinkId": "int",
    "Amount": "int",
    "Status": "text",
    "IsFullPaymentAmount": "bool",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_Status": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "paymentterms": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "PTID": "text",
    "AdminFee": "int",
    "DLDFee": "int",
    "Name": "text",
    "ExchangeRate": "int",
    "Status": "bool",
    "Currency": "text",
    "BedType": "text",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_Name": "ev.vector",
    "embed_Status": "ev.vector",
    "embed_BedType": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "paymenttermitems": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "Name": "text",
    "Gap": "int",
    "Percentage": "int",
    "DueDate": "text",
    "PaymentTermId": "int",
    "MilestoneGapType": "text",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "embed_Name": "ev.vector",
    "embed_MilestoneGapType": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "projectpaymentplans": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "ProjectId": "int",
    "PaymentTermId": "int",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "projectpaymentterms": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "Layout": "text",
    "ProjectId": "int",
    "MinimumAmount": "decimal",
    "embed_Layout": "ev.vector",
    "row_txt": "text",
    "embedding": "ev.vector"
  }},
  "projectpayment": {
            "domain": "payments",
        "columns":{
    "Id": "int",
    "ProjectId": "int",
    "Layout": "text",
    "MinimumAmount": "decimal",
    "projectid": "int4",
    "projectname": "text",
    "projectshortname": "text",
    "projectdeveloperid": "int4",
    "projectaddress": "text",
    "projectlocation": "text",
    "projectstatus": "text",
    "projectaccountnumber": "text",
    "projectbankaddress": "text",
    "projectbankbranch": "text",
    "projectbankname": "text",
    "projectadminfee": "text",
    "projectcorporateaccountname": "text",
    "projectcorporateaccountnumber": "text",
    "projectcorporatebankaddress": "text",
    "projectcorporatebankbranch": "text",
    "projectcorporatebankname": "text",
    "projectcorporateibannumber": "text",
    "projectescrowaccountname": "text",
    "projectibannumber": "text",
    "projectcurrency": "text",
    "projectisavailabiletoportal": "text",
    "projectlatitude": "text",
    "projectlongitude": "text",
    "embed_projectname": "ev.vector",
    "embed_projectshortname": "ev.vector",
    "embed_projectlocation": "ev.vector",
    "embed_projectbankaddress": "ev.vector",
    "embed_projectbankbranch": "ev.vector",
    "embed_projectbankname": "ev.vector",
    "embed_projectcorporateaccountname": "ev.vector",
    "embed_projectcorporatebankaddress": "ev.vector",
    "embed_projectcorporatebankbranch": "ev.vector",
    "embed_projectcorporatebankname": "ev.vector",
    "embed_projectescrowaccountname": "ev.vector",
    "embed_projectisavailabiletoportal": "ev.vector",
    "embed_projectlatitude": "ev.vector",
    "embed_projectlongitude": "ev.vector",
    "CreatedBy": "text",
    "CreationDate": "text",
    "IsDeleted": "bool", 
    "row_txt": "text",
    "embedding": "ev.vector"
  }}
}


# WORD/PARTIAL SEARCH authorization (by domain → table → columns)
word_search_list: Dict[str, Dict[str, List[str]]] = {
    
        "developers": ["portalaccesstype"],
        "projects":   [ "status", "isavailabiletoportal"],
        "buildings":  ["availabilitystatus", "availab", "bedroom", "currency", "status", "isavailabiletoportal"],
        "units":      ["availabilitystatus",  "currency", "baths", "bedroom" , "furnished", "kitchen",   "type",],
        
        "employees": ["portalstatus", "status",  ],
        "directors_employees": ["director_portalstatus",  "director_status", "hos_portalstatus",    "hos_status"],
        "hos_employee":["portalstatus",    "status" ],
        "brokers":   [ "stage", "city", "country"],
        "teams":     [ ],
        "agents_employee":  ["portalstatus",   "status" ],
       
        "customers": [ "country", "city",  "status"],
        "customerrequesttrackers": ["lable", "status"],
        "customers_deals" : [ "name",  "stage", "status",  "country", "city",],


        "deals": [ "name", "type", "stage",  "status", "city", "country"],
        "deals_customers": [ "country", "city", "status"],
        "deals_units": [ "stage", "status", "salesleadsource", "availabilitystatus", "bedroom","furnished","kitchen","parking", "currency","type",  "availability", "bookingtype",],
        "deals_projects": [ "salesleadsource", "stage", "status", "isavailabiletoportal", ],     
        "deals_directors": ["director_portalstatus",   "director_status", "hos_portalstatus",   "hos_status"],
        "deals_agents":  ["portalstatus",  "status" ],

        "bookings": ["Stage", "layout", "TransferredToDeal",  ],

        "paymentlinks": ["paymenttype", "status", "currency" ],
        "paymentsplits":[ "status",], 
        "payments":["paymentreceiptdetailsname", "status", "account", "paymentmethod", 
                    "chqddttnumber",  "currency", "paymentstatus",   ], 

        "paymentplandetails":[], 
        "onlinepaymenttransactions":["status"], 
        "installmentplans":["name", "status", "accounttype", ], 
        "instalmentadjusted":["instalmenttype", "paymentmethod", "accounttype", ],
        "paymenttermitems":["name", "milestonegaptype", ], 
        "paymentterms":["name", "bedtype", "status", "currency"], 
        "projectpaymentplans":[], 
        "projectpaymentterms":["layout", ],
}


operation_search_list : Dict[str, Dict[str, List[str]]] = {
    "developers": ["id", "phone", "portalaccesstype", "registrationnumber"],
    "projects":["id","developerid", "accountnumber", "adminfee", "corporateaccountnumber", 
                "corporateibannumber", "ibannumber",  "latitude", "longitude" ],
    "buildings": ["id", "developerid", "projectid", "accountnumber", "ibannumber", "paymenttermid", "latitude", "longitude" ],
    "units": ["id", "number", "buildingid", "unitclusterid", "baths", "floor", "layouthashcode","plotnumber",
                "area", "price", "pricepersqft", ],

    
    "employees": ["id", "mobile", "empcode", "reportingmanagerid",  "email",  ],
    "directors_employees": ["director_id", "director_mobile", "director_empcode", "director_reportingmanagerid", 
                           "director_sap",   "director_email", "hos_email",
                            "hos_id", "hos_mobile", "hos_empcode", "hos_reportingmanagerid", ],
    "hos_employee": ["id", "mobile", "empcode", "reportingmanagerid", "email", ],
    "brokers": ["id", "phone","zipcode", "emiratesid", "brokeragecompanyid",  "email",
                "passportnumber", "representativeemail", "representativemobile",
                "representativename", "tradelicensenumber", "userssoid",],
    "agents_employee" :["id", "mobile", "empcode", "reportingmanagerid", "teamid", "sap",  "email"],
    "teams": [],
   

    "customers": ["id", "mobile","mobilecountrycode","alternativemobileno","alternativemobilecountrycode", "email", "street", 
                "landline", "phone", "apartment","buildingno","postalcode" , "ownershippercentage"],
    "customerrequesttrackers": ["id", "customerid", "actioncount", "isactive", "roleid", "order"],
    "customers_deals" : [  "customer_id", "id", "directorid", "agentid", "unitid",   "street",],
    

    "deals": ["id", "directorid", "agentid", "unitid", ], 
    "deals_units": ["deal_id",  "directorid", "agentid", "id", "buildingid",  "unitclusterid", "price_range",
                    "area", "price",  "pricepersqft",  "number","baths","floor", "salesoffer", "paymentmodel", "unitnumber",  ],
    "deals_projects": [  "id",  "directorid",  "agentid",  "unitid",  "bookingtype", "stage",
                        "status", "originalprice",  "deal_id",  "latitude", "longitude" ],
    
    "deals_customers": ["deal_id","id", "mobile","mobilecountrycode","alternativemobileno","alternativemobilecountrycode",  "email",  "street",
                        "landline", "phone", "apartment","buildingno","postalcode" , "ownershippercentage"],

    "deals_agents" :["deal_id", "id", "mobile", "empcode", "reportingmanagerid",  "teamid",   "email", "sap" ],
    "deals_directors": ["deal_id","director_id", "director_mobile", "director_empcode", "director_reportingmanagerid", 
                            "director_sap",   "director_email",  "hos_email",
                            "hos_id", "hos_mobile", "hos_empcode", "hos_reportingmanagerid", ],


    "bookings": ["id", "unitid",  "originalprice", "agreedprice", "customerid",
										"projectid",  "agentid",  "managerid", "headofsalesid", "csoid",
										"brokerid",  "createdby",  "isdeleted", "paymentlinkid", "bookingreferenceid", "draftedamount"],
    "paymentlinks": ["id", "amount", "payment_url", "ref_no",  "payment_link_reference_id",
                     "project_id", "agent_id", "created_by",  "is_deleted",  "is_splited", "remaining_amount", "service_charge_percentage"],
    "paymentsplits":["id", "PaymentLinkId", "amount", "isfullpaymentamount", "createdby","isdeleted", ], 
    "payments":["id", "amount", "dealid", "popreference","isformrequested", "isloading","customerid","createdby","isdeleted",  ],  
        "paymentplandetails":["id", "salesproposalid", "paymenttermitemid", "amount", "percentage" ,"createdby","isdeleted", ], 
        "onlinepaymenttransactions":["id", "businessentityid", "businessentitytype",   "amount", "transactionnumber"], 
        "installmentplans":["id", "priority", "percentage", "amount",  "settled", "paidamount", "remainingamount", "dealid",  "createdby","isdeleted", ], 
        "instalmentadjusted":["id", "amount",   "paymentid", "instalmentplanid", "currency",  "createdby","isdeleted", ],
        "paymenttermitems":["id",  "gap", "percentage",   "paymenttermid"], 
        "paymentterms":["id", "ptid", "adminfee", "dldfee", "exchangerate",   "createdby","isdeleted", ], 
        "projectpaymentplans":["id", "projectid", "paymenttermid", "createdby","isdeleted", ], 
        "projectpaymentterms":["id", "projectid", "minimumamount",   ],
  }   

# SEMANTIC SEARCH columns (MUST align to available embed_* columns)
semantic_search_list: Dict[str, Dict[str, List[str]]] = {
    
        "developers": ["name", "operatorname"],  # only columns with embeddings
        "projects": [  "name", "shortname", "location", "bankaddress", "bankbranch", "bankname",
            "corporateaccountname", "corporatebankaddress", "corporatebankbranch",
            "corporatebankname", "escrowaccountname",  "address" ],
        "units": [ "name", "shortname",   "description",  "view",  ],
        "buildings": [ "name", "shortname", "location", "bankaddress", "bankbranch",
            "bankname", "escrowaccountname","address"  ],
               
        
        "employees": ["name", "nationality", "address", "role", "position", "department", "section"],
        "hos_employee": ["name", "nationality", "address", "role", "position", "department", "section"],
        "directors_employees": ["director_name", "director_nationality", "director_address", "director_role", "director_position", "director_department", "director_section",
                                "hos_name", "hos_nationality", "hos_address", "hos_role", "hos_position",  "hos_department", "hos_section"],
        "teams": ["name"],
        "agents_employee":["name", "nationality", "address", "role", "position", "department", "section"],
        "brokers": ["name", "nationality", "address", "evrepresentativename" ],
        
        
        "customers": ["fullnameen", "fullnamear", "nationality",  "companynamear", "companynameen", "operatorname", "position",],
        "customerrequesttrackers": ["rolename"],
        "customers_deals": [  "fullnameen",  "fullnamear",  "nationality", "companynamear",  "companynameen",  "operatorname",
                            "position",  "deal_name",  "projectname", "accountmanagername",  ],

        "deals": ["address", "role", "position", "section", "department", "nationality", ],
        "deals_units": [   "deal_name",  "projectname" , "paymentmodel", "contactname",  "agentfreelancername",
                         "accountmanagername",  "unit_name",   "description",  "unit_view",  "project",  "booking",   ],

        "deals_projects":[  "name",   "projectname",  "accountmanagername", "contactname", "agentfreelancername", "project_name",
                          "project_shortname",  "project_location",   "bankaddress", "bankbranch",  "bankname", "corporateaccountname",
                         "corporatebankaddress", "corporatebankbranch", "corporatebankname",  "escrowaccountname",  ],

        "deals_directors": ["director_name", "director_nationality", "director_address", "director_role", 
                                "director_position", "director_department", "director_section",
                                "hos_name", "hos_nationality", "hos_address", "hos_role", "hos_position",
                                  "hos_department", "hos_section"],

        "deals_agents":["name", "nationality", "address", "role", "position", "department", "section"],
        "deals_customers" :["fullnameen",  "fullnamear",  "nationality", "companynamear",  "companynameen",  "operatorname",
                            "position",  "deal_name",  "projectname", "accountmanagername", ],

        "bookings" : [],
        "paymentlinks": [],
        "paymentsplits":[], 
        "payments":[], 
        "paymentplandetails":["evinstalment"], 
        "onlinepaymenttransactions":[], 
        "installmentplans":[], 
        "instalmentadjusted":[],
        "paymenttermitems":[], 
        "paymentterms":[], 
        "projectpaymentplans":[], 
        "projectpaymentterms":[],

}

datetime_search_list : Dict[str, Dict[str, List[str]]] = {
    
        "developers": [ ] ,
        "projects": [ ],
        "units": [   ],
        "buildings": [   ],
               
        
        "employees": [ "employmentdate", ],
        "hos_employee": [  "employmentdate",],
        "directors_employees": [  "director_employmentdate","hos_employmentdate", ],
        "teams": [ ],
        "agents_employee":[  "employmentdate",],
        "brokers": [  "passportissueddate" , "passportexpirydate", ],
        
        
        "customers": [ ],
        "customerrequesttrackers": [ ],
        "customers_deals": [    ],

        "deals": [  ],
        "deals_units": [   "bookingdate",   ],

        "deals_projects":[ "bookingdate", ],

        "deals_directors": ["director_employmentdate", "hos_employmentdate", ],

        "deals_agents":[ "employmentdate",],
        "deals_customers" :[    ],

        "bookings" : ["creationdate",],
        "paymentlinks": ["expiry_date", "creation_date",],
        "paymentsplits":[ "creationdate",], 
        "payments":["dateofreceipt", "dateoftransaction", "chequedepositdate", "chequereturneddate",
                    "receivedbyevdate", "transferredtodeveloperdate", "receiveddate", "creationdate", ], 
        "paymentplandetails":["duedate", "creationdate", ], 
        "onlinepaymenttransactions":["creationdatetime", ], 
        "installmentplans":["duedate", "paymentdate",  "creationdate",], 
        "instalmentadjusted":["creationdate",],
        "paymenttermitems":["duedate"], 
        "paymentterms":[ "creationdate",], 
        "projectpaymentplans":[ "creationdate",], 
        "projectpaymentterms":[],

}
